name: Create Pr

on:
  push:
    branches: [ 'formula/**' ]

jobs:
  build:
    name: Create Pr to Update Formula
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: pull-request
      id: cpr
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        pr_title: "momento-cli ${{ github.ref }}"
        pr_body: ":crown: *Automated PR*"
        pr_label: "automation"
        pr_draft: false
        pr_allow_empty: true
        github_token: ${{ secrets.MOMENTO_MACHINE_USER_GITHUB_TOKEN }}
